### ISSUE TITLE
Issue with Nested Routers

### ISSUE THREAD

**Issue by izzybelll** [chibisov/drf-extensions#100]
I followed the snippets of coding from the example for the Nested Routers extension, but when I do something like /posts/2/comments/ it returns ALL the comment objects I have in my database. It won't return just the comments for my post object with id "2." Is there something I need to do in the queryset for the Viewsets????

**Comment by chibisov** [comment]
Please, show me your views and routers implementation.

**Comment by auvipy** [comment]
closing as lack of activities
