### ISSUE TITLE
AssertionError at /api-root/post/ for Nested Routers

### ISSUE THREAD

**Issue by izzybelll** [chibisov/drf-extensions#101]
I upgraded to DRF 3.0 with Python 2.7 on Django 1.8 and I'm getting this error when I try to access the api page:

AssertionError at /api-root/post/
'PostViewSet' should either include a `queryset` attribute, or override the `get_queryset()` method.'

Is the Nested Router extension not compatible with DRF 3.0? It works fine on DRF 2.4 but I only got this error when I upgraded the DRF.

**Comment by auvipy** [comment]
is the problem still valid?
