### ISSUE TITLE
Any plan to upgrade drf-extensions for django 1.8 and DRF 3.2?

### ISSUE THREAD

**Issue by nemesisdesign** [chibisov/drf-extensions#103]
Is there any plan to upgrade drf-extensions for django 1.8 and DRF 3.2?

Are contributions wanted? If yes are there any suggestions?

**Comment by auvipy** [comment]
should be drf 3.3 now

**Comment by auvipy** [comment]
#113

**Comment by auvipy** [comment]
yes will be updated to drf 3.3.x and latest django release

**Comment by auvipy** [comment]
d08425c8db7061e32303f3caf041aa322fcc8382 updated
