### ISSUE TITLE
remove support of django less then 1.7 as latest drf do that

### ISSUE THREAD

**Issue by auvipy** [chibisov/drf-extensions#113]

**Comment by codingjoe** [comment]
:+1: I would only support the latest Django version. If someone needs to support an older version, he can always use an older release of this package. Makes developing easier.

**Comment by auvipy** [comment]
well you need to support all the maintained version of django. like 1.8 is an LTS, but the versions less then 1.7 are officially End of their life cycle and should be upgraded to LTS/more newer version :)

**Comment by codingjoe** [comment]
You don't have to, you can. I would exclude LTS versions. That would have meant support for 1.4 until April this year. Oh hell no! :-1:

**Comment by auvipy** [comment]
1.8 LTS for 3 years :p and a new LTS in every 3 years

**Comment by auvipy** [comment]
resolved with d08425c8db7061e32303f3caf041aa322fcc8382
