### ISSUE TITLE
Move the project under a new github organisation for allow more volunteers to help maintain the project.

### ISSUE THREAD

**Issue by auvipy** [chibisov/drf-extensions#114]
seems good option? @chibisov

**Comment by chibisov** [comment]
Good option. Any idea for organisation?

**Comment by auvipy** [comment]
yeah!!! lets create a new github orga naming drf-extensions, after creating that going on this projects setting select transfer ownership (you will remain the bdfl of the project and can select some volunters with specific authority via github ) and move the project under new org. all the issues should be auto migrated in the new org. as its a fairly smaller project issues introduced by migration [if any, i hope not] those could easily be fixed. having more then one maintainer will help reviewing issues/pull reqs from contributors and regular maintenace of the project with DRF :dancer:

**Comment by auvipy** [comment]
didn't like? @chibisov

**Comment by chibisov** [comment]
Why should I create new organization? I could just invite some collaborators with permissions for merging pullrequests, no?

**Comment by auvipy** [comment]
thats ok too!!! :)

**Comment by chibisov** [comment]
#115
