### ISSUE TITLE
Looking for the new core collaborators

### ISSUE THREAD

**Issue by chibisov** [chibisov/drf-extensions#115]
I've been working with Django and Django Rest Framework for years. `drf-extensions` is the most valuable contribution I've ever made to open source. But these day I don't use Django for my daily job and don't have time to review pool requests or resolve issues. `drf-extensions` have been used by hundreds of companies and developers. I think it's time to move on and I'm looking for the new core collaborators. They will have full access for merging pull requests and publish new versions of `drf-extensions` to pypi.

If you want to help to DRF community then reply to this issue or write me a letter (web-chib@ya.ru) why you think you are ready to be the core collaborator.

**Comment by auvipy** [comment]
contacted!

**Comment by auvipy** [comment]
I sent you a mail.
