### ISSUE TITLE
Last commit is over two months

### ISSUE THREAD

**Issue by adminq80** [chibisov/drf-extensions#124]
Hey guys,

Thanks for doing this, but I would like to know if this project is still active or not.

Abdulrahman

**Comment by auvipy** [comment]
It's still active. as you know I'ts an open source project so maintainers are not bound to work if they don't have time. You are welcome to contribute.

**Comment by adminq80** [comment]
Yah I know I just wanted to make sure it's alive before I started using it.

**Comment by auvipy** [comment]
work for supporting django 1.9 version is going on.

**Comment by gustavi** [comment]
`matser` now supports Django 1.9. Could you make a release ?
