### ISSUE TITLE
@list_route and @detail_route url_path parameter breaks ExtendedSimpleRouter

### ISSUE THREAD

**Issue by danpoland** [chibisov/drf-extensions#128]
The list route and detail route decorators work fine on ViewSets routed by the ExtendedSimpleRouter except when you use the url_path argument in the decorators.

The following exception is thrown:
TypeError: MyViewSet() received an invalid keyword 'url_path'

**Comment by danpoland** [comment]
If I can find time in the next few weeks I will take a crack at this.

**Comment by auvipy** [comment]
please feel free

**Comment by greemo** [comment]
Any progress on this? I have just hit this issue and was going to look at it myself to see how complicated the patch will be.

**Comment by greemo** [comment]
Actually, I'm working on it now.

**Comment by greemo** [comment]
I totally adapted the code to the latest django rest @list_route and @detail_route specifiers. The code could be cleaned up further, but for the moment, this got me going...

**Comment by greemo** [comment]
This issue is fixed on the current master branch - https://github.com/chibisov/drf-extensions/commit/0a82b4c57ab95e53c56e5e71cfe71f5a33812a65

**Comment by auvipy** [comment]
closing as fixed
