### ISSUE TITLE
Minimum requirements?

### ISSUE THREAD

**Issue by kevin-brown** [chibisov/drf-extensions#154]
The README currently alludes to the following minimum requirements

- DRF 2.3.8+/3.0.0+
- Django 1.5+
- Python 2.7/3.4/3.5

But the `setup.py` suggests a minimum DRF version of 3.3.1 and the tests suggest a minimum Django version of 1.8.

What are the actual minimum requirements to use this package?

**Comment by auvipy** [comment]
that is for present version available on pypi. the masters branch supports newer versions.
