### ISSUE TITLE
Is python 2.7 not supported with latest releases ? 

### ISSUE THREAD

**Issue by Sshuichi** [chibisov/drf-extensions#155]
I'm using Django 1.9.7, DRF 3.3.3 with Python 2.7, action decorators don't seem to work, when I set the endpoint parameter to change the url name.

>master branch is supported with django 1.8 and 1.9 and drf 3.3.* only with python 3.5

Does that mean that it won't work for my setup ?

**Comment by auvipy** [comment]
2.7 is supported along with 3.5 and 3.4

**Comment by auvipy** [comment]
action decorators wont be working as they are deprecated in favor of drf's detail-route

**Comment by Sshuichi** [comment]
Tha ks @auvipy , how to achieve the same function of actions with the drf decorators ?
