### ISSUE TITLE
drf-extensions fails with 'cannot import name 'patterns'' error on django 1.10

### ISSUE THREAD

**Issue by TurashovAndrey** [chibisov/drf-extensions#162]
drf-extensions fails with the next error on django 1.10:

Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f80e9ede598>
Traceback (most recent call last):
File "/lib/python3.4/site-packages/rest_framework_extensions/compat.py", line 22, in <module>
from django.conf.urls import patterns, url, include
ImportError: cannot import name 'patterns'

**Comment by auvipy** [comment]
please try the master branch and then report what issues you are facing with drf-ext

**Comment by TurashovAndrey** [comment]
With the latest master everything works correctly. Thanks.
