### ISSUE TITLE
No module named 'django.conf.urls.defaults'

### ISSUE THREAD

**Issue by lwm** [chibisov/drf-extensions#163]
```
    from rest_framework_extensions.compat import force_text
  File "/home/lwm/work/noa/velodrome/.venv/src/drf-extensions/rest_framework_extensions/compat.py", line 24, in <module>
    from django.conf.urls.defaults import patterns, url, include
ImportError: No module named 'django.conf.urls.defaults'
```

PR on the way ...

**Comment by lwm** [comment]
Oh, my error, [it's already fixed](https://github.com/chibisov/drf-extensions/blob/0306a3ab934e6c5f31603e7f452742ac9a5c7c28/rest_framework_extensions/compat.py#L24). Just something local.

**Comment by SkinyMonkey** [comment]
I'm having the same issue.
Using drf last version and drf-extensions last version installed with pip

Could you please explain to me what's going on?

**Comment by SkinyMonkey** [comment]
I'll try.

Thank you! :)
