### ISSUE TITLE
Not compatible with Django 1.10

### ISSUE THREAD

**Issue by pga23** [chibisov/drf-extensions#164]
ImportError: No module named 'django.conf.urls.defaults'
in rest_framework_extensions/compat.py
after upgrade from Django 1.9.9 to Django 1.10

**Comment by auvipy** [comment]
plz try master branch

**Comment by rudigiesler** [comment]
I have the same problem. @auvipy the master branch fixes it for me, is it possible to get a release to PyPI?

**Comment by auvipy** [comment]
the problem is we need to update a lot of test, but don't have the time.

**Comment by joeyespo** [comment]
@auvipy 

> the problem is we need to update a lot of test, but don't have the time

Any way to publish a "beta" release to PyPI in the meantime?

Django-polymorphic [did that](https://github.com/django-polymorphic/django-polymorphic/issues/225) for [the same reasons](https://github.com/django-polymorphic/django-polymorphic/issues/225#issuecomment-241655755) and it was very helpful.

**Comment by auvipy** [comment]
Hi, I am a co maintainer of this project though do all the house keeping now a days, but I don't have the pypi release key access right now, and the creator of the project won't let publish anything if test keep failing. we need to fixed many test failures first. fixing the 1.8 ones will certainly fix a lot of 1.8, 1.9 and 1.10 branch. problem is I don't have much time so looking for contributors and I will review and merge them as fast as I can.

**Comment by auvipy** [comment]
you could try from master branch in the mean time

**Comment by cerberusaeon** [comment]
How's this coming along?

**Comment by garykrige** [comment]
Works for me with this fix #165
