### ISSUE TITLE
0.4.0 release

### ISSUE THREAD

**Issue by auvipy** [chibisov/drf-extensions#173]
@chibisov could you please have a look?

**Comment by chibisov** [comment]
Give me some time for a review (2 or 3 days)

**Comment by auvipy** [comment]
ok

**Comment by chibisov** [comment]
Depends on #171

**Comment by auvipy** [comment]
yes

**Comment by chibisov** [comment]
I've reverted the pull and have some questions about it here #175

**Comment by dsteinberger** [comment]
Hello, do you know when this release will be made, please ?

**Comment by trojkat** [comment]
Any progress on this?

**Comment by auvipy** [comment]
I will be adding dj 1.11 support and probably then a new release could occure

**Comment by jkeyes** [comment]
Any news on when a new release will be uploaded to PyPi?

**Comment by sfdye** [comment]
Any update on this and #175 please? kinda need etag in one of our projects.

**Comment by auvipy** [comment]
https://github.com/chibisov/drf-extensions/pull/209 hopefully after completing this we could roll out a new release

plz review guy

**Comment by sfdye** [comment]
I guess new release is on the way 👍

**Comment by auvipy** [comment]
still few tests need to be fixed. check the latest pr and read the travis log to come up with fix suggestion

**Comment by auvipy** [comment]
3.2 is 4.0 actually :D 30 april is the deadline

**Comment by dtougas** [comment]
Is this release still happening today? I am hoping so, as I am running into a Django 2.0 issue that I hope will be resolved with this release...

**Comment by auvipy** [comment]
ww have to revert one change and update some changelog,. in the mean time please

**Comment by linuxlewis** [comment]
Anything we can do here to make this release happen? Happy to pitch in

**Comment by auvipy** [comment]
yes plz, revert this commit https://github.com/chibisov/drf-extensions/commit/ed0f4151fb6b0f2998081b42143e8037f1f5732d and put them as before, but ignore from tests so that travis is green, and mention in docs that the implementation has design issues so use with your own risk. and lastly update the changelog for other issues changed since last release.

**Comment by ramsrib** [comment]
Any rough timeline for this new release (seems like it's pending for couple of months)? Since the existing release (`0.3.1`) doesn't support `Django 2`,  It would be nice, if you guys release a new version just to support `Django 2`. Thanks

**Comment by JesusAnaya** [comment]
I had to use the develop version for can upgrade one project to Django 2, please think in release soon an official version for support Django 2, thank you.

**Comment by ramsrib** [comment]
I switched to `drf-nested-routers` since this releasing doesn't seems to be happening in near future.

**Comment by auvipy** [comment]
it's released. going to drop python 2 support for next release.
