### ISSUE TITLE
Latest package of drf-extensions?

### ISSUE THREAD

**Issue by JoelGoh92** [chibisov/drf-extensions#202]
I noticed that there were some code changes, such as the updates to the etags mixins,  which are not present in the publicly available 0.3.1 drf-extensions package, so I was wondering if the package would be updated soon?

**Comment by auvipy** [comment]
we should a new release within few months but feel free to use from master

**Comment by JoelGoh92** [comment]
@auvipy Noted, thanks! Looking forward to the new release!
