### ISSUE TITLE
master branch build is broken

### ISSUE THREAD

**Issue by mmautner** [chibisov/drf-extensions#207]
As indicated by the travis icon:

https://travis-ci.org/chibisov/drf-extensions

Looks like it broke when @auvipy merged this PR to support Django 1.11: https://github.com/chibisov/drf-extensions/pull/197

https://travis-ci.org/chibisov/drf-extensions/builds

**Comment by mmautner** [comment]
Perhaps 1.11 should be removed from Tox tests until this issue is addressed? https://github.com/chibisov/drf-extensions/issues/187

**Comment by auvipy** [comment]
in the mean time review the pr https://github.com/chibisov/drf-extensions/pull/209
