### ISSUE TITLE
Incompatibility with drf 3.8.1

### ISSUE THREAD

**Issue by ding1992** [chibisov/drf-extensions#211]
Hi folks,

Noticed that DRF 3.8.0 has removed `replace_methodname` function in `routers.py` [#5705](https://github.com/encode/django-rest-framework/pull/5705), which is referenced in `drf-extensions` routers.
Really appreciate if this can be fixed soon. 
Thanks!

**Comment by sfdye** [comment]
I am facing this too

**Comment by dennypenta** [comment]
It also has effect with Django 2.0
To reproduce:

`from rest_framework_extensions.routers import NestedRouterMixin`

So you will get:

` No module named 'django.core.urlresolvers'`

**Comment by auvipy** [comment]
what does master branch says? with 3.8.1?

**Comment by rpkilby** [comment]
Hi all, I've submitted #214 which should fix compatibility with the latest version of DRF. If you could try out the branch and report any router-related errors, that would be helpful. Thanks!

**Comment by sfdye** [comment]
@rpkilby Thanks very much for this, but the test is failing.

**Comment by sfdye** [comment]
@rpkilby Never mind, I just saw #215 great effort!
