### ISSUE TITLE
ImportError: cannot import name 'replace_methodname'

### ISSUE THREAD

**Issue by blokfyuh** [chibisov/drf-extensions#212]
There is a good chance that DRF removed this method from its new release 3.8.1. It was working until version 3.7.7.

If you don't have time to tackle this issue, I could create a PR. Let me know.

Thanks and have a good one.

**Comment by auvipy** [comment]
plz send a PR and check other failing tests too. I will review soon

**Comment by auvipy** [comment]
send a PR and ping me https://github.com/chibisov/drf-extensions/issues/211 here, closing it as duplicate
