### ISSUE TITLE
Pypi version not working with Django 1.10

### ISSUE THREAD

**Issue by juanpaps03** [chibisov/drf-extensions#218]
This is a bug on version 0.3.1, the file rest_framework/routers.py is importing patterns from django urls, this function is not in Django 1.10.

The doc says that support django 1.10

**Comment by auvipy** [comment]
master is django 1.11 now, and django 1.10 is end of life

**Comment by juanpaps03** [comment]
Okay, I already installed from master, I think important to update the pypi version.

Thanks
