### ISSUE TITLE
urlresolvers Django 2 - pip

### ISSUE THREAD

**Issue by Calion54** [chibisov/drf-extensions#224]
Hi,

Why is the installation of the library with pip not at the same level as the master?
it's annoying for a production.

Best regards,

**Comment by zulrang** [comment]
Maintainer claims they don't have time to push to PyPI: https://github.com/chibisov/drf-extensions/issues/206

**Comment by camflan** [comment]
@auvipy I understand you're busy, hoping to keep this active though. Installing off master is not great

**Comment by auvipy** [comment]
I got the response. he was busy, he will release after I add release notes. so very soon for a pypi release hopefully
