### ISSUE TITLE
version 0.3.1 is not compatible with DRF 3.8 and produces ImportError

### ISSUE THREAD

**Issue by jberends** [chibisov/drf-extensions#226]
The version 0.3.1 is not compatible with DRF 3.8. It seems that the master is, but the latest provided release to PyPI apparently not.

It produces an import error in the 0.3.1 code

Error:
```
  ...
  File ".../site-packages/rest_framework_extensions/routers.py", line 7, in <module>
    from rest_framework.routers import (
ImportError: cannot import name 'replace_methodname'
```

Culprit code of 0.3.1
```python
# -*- coding: utf-8 -*-
from distutils.version import StrictVersion
from django.core.exceptions import ImproperlyConfigured
from django.core.urlresolvers import NoReverseMatch

import rest_framework
from rest_framework.routers import (
    DefaultRouter,
    SimpleRouter,
    Route,
    replace_methodname,
    ^^^^^^^^^^^^^^^^^^^
)
```

**Comment by travis-cramer** [comment]
I've run into the same error. Running drf 3.8.2

**Comment by auvipy** [comment]
you need to install from master master support 3.8

**Comment by TheSaltman** [comment]
It still would be nice to get this in pypy.

**Comment by jberends** [comment]
yup. Why not package it and release it as a proper release?

--
Jochem Berends

jberends@jbits.nl
The Hague

**Comment by auvipy** [comment]
lack of time

**Comment by jberends** [comment]
Is there anything that we can help you with?
Maybe automate the build and upload of packages eg. using `twine`

I can make a PR...

```
pip install twine
python setup.py bdist_wheel --universal
twine upload dist/*.whl
```

**Comment by auvipy** [comment]
need to revert one commit and some release notes remain actually

**Comment by bryson** [comment]
Can you add instructions for installing from git to the README at least?

**Comment by auvipy** [comment]
I will

**Comment by adrienrusso** [comment]
Same issue here, Still waiting for a new version.

**Comment by auvipy** [comment]
i have emailed the original author for a new pypi release.

**Comment by adrienrusso** [comment]
0.4.0 has been released 15 hours ago. Thanks

**Comment by auvipy** [comment]
please let me know if the pypi release is working well. it's my first release of this package

**Comment by adrienrusso** [comment]
I have no issue so far. It passes all our checks.

**Comment by auvipy** [comment]
awesome!
