### ISSUE TITLE
Please tag the 0.4.0 release so that we can use it in requirements.txt

### ISSUE THREAD

**Issue by thesunlover** [chibisov/drf-extensions#227]
There is no working release for python 3.5+ For Django 2.0+.
Would you please tag the current master as a new version as it is title in the "pip list" with the version 0.4.0
Thanks in advance

**Comment by jberends** [comment]
dupe of #226

**Comment by thesunlover** [comment]
for those of you who are waiting for the pip install:
add this one (it does the work for me): 

git+http://github.com/chibisov/drf-extensions.git@00712396be979aaa5a86246bee39284b5e5e8d71#egg=drf-extensions
