### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by hsmett** [chibisov/drf-extensions#254]
Hello dear maintainers,

First of all, thank you for your work!

There have been a lot of changes since the 0.4.0:
https://github.com/chibisov/drf-extensions/compare/0.4.0...master

I'd like to know if you could plan a new release, introducing django 2.1 & 2.2 and DRF 3.9 support.

Thank you in advance.

**Comment by auvipy** [comment]
I will try to release ASAP

**Comment by auvipy** [comment]
git tagged and pushed to pypi! enjoy

**Comment by auvipy** [comment]
please donate https://opencollective.com/drf-extensions#backer
