### ISSUE TITLE
Nested routes are not generated in API documentation

### ISSUE THREAD

**Issue by kwasielew** [chibisov/drf-extensions#258]
Hello,

I'm using Django Rest Framework for creating API and wanted to use `drf-extensions` for nested routes functionality and it was fine.
But there is one issue that nested routes are not documented by `include_docs_urls`.
Is there something that I missed or it simply is not compatible with nested routes?
Thanks for answers

djangorestframework==3.9.0
drf-extensions==0.5.0
Python2.7

**Comment by auvipy** [comment]
0.5.0 do not support python 2.7 or 3.4
