### ISSUE TITLE
CacheResponse assumes a pickle serializer is used, breaking on any other serializers

### ISSUE THREAD

**Issue by gcbirzan** [chibisov/drf-extensions#267]
As per the WSGI spec, headers must be a list of tuples. If you use a serialization format that doesn't support tuples (i.e. any that's not pickle), headers will end up being a list of lists. This then breaks if you try to use % to format the values. 

https://github.com/chibisov/drf-extensions/blob/437926b91989e402ef0824c15d54f09d989d2f1a/rest_framework_extensions/cache/decorators.py#L99

This is the bit of code that causes this. A solution would be to iterate through the headers and use \_\_setitem__ as that will take care of putting tuples.

**Comment by auvipy** [comment]
PR is welcome :)
