### ISSUE TITLE
Old version from pip install

### ISSUE THREAD

**Issue by ruslankrivoshein** [chibisov/drf-extensions#277]
When I install it via `pip install drf-extensions`, I get the version of code from before [this](https://github.com/chibisov/drf-extensions/commit/1d28a4b28890eab5cd19e93e042f8590c8c2fb8b#diff-65da42d61ad1e3b53131efd606a7d2b8) commit. I mean the code has dependency from django's six package.

**Comment by ruslankrivoshein** [comment]
pip 19.3.1
virtualenv 16.7.8
drf-extensions 0.5.0

And when I install it directly from GitHub `pip install git+git://github.com/chibisov/drf-extensions`, it is delivered nice.

**Comment by eeezae** [comment]
same

**Comment by ruslankrivoshein** [comment]
Please, get in live...

**Comment by auvipy** [comment]
try https://pypi.org/project/drf-extensions/0.7.0/
