### ISSUE TITLE
cannot import name 'ListDestroyModelMixin' from 'rest_framework_extensions.mixins'

### ISSUE THREAD

**Issue by DawsonLey** [chibisov/drf-extensions#284]
```ImportError: cannot import name 'ListDestroyModelMixin' from 'rest_framework_extensions.mixins' ```

Solved by changing ```from rest_framework_extensions.bulk_operations.mixins import ListUpdateModelMixin```

to 

```from rest_framework_extensions.bulk_operations.mixins import ListUpdateModelMixin, ListDestroyModelMixin```

in ```rest_framework_extensions/mixins.py``` file

**Comment by OskarPersson** [comment]
Fixed in #260
