### ISSUE TITLE
EmptyResultSet removed in Django 3.1

### ISSUE THREAD

**Issue by henriklindgren** [chibisov/drf-extensions#294]
Version:
drf-extensions 0.6.0
Django 3.1
(python 3.8, but doesn't matter for issue)

Description:
Django has removed EmptyResultSet backward compatibility.
django 3.1 commit breaking drf-extensions:
https://github.com/django/django/commit/129583a0d3cf69b08d058cd751d777588801b7ad

Error:
`from rest_framework_extensions.key_constructor import bits
  File "/usr/local/lib/python3.8/site-packages/rest_framework_extensions/key_constructor/bits.py", line 3, in <module>
    from django.db.models.sql.datastructures import EmptyResultSet
ImportError: cannot import name 'EmptyResultSet' from 'django.db.models.sql.datastructures' (/usr/local/lib/python3.8/site-packages/django/db/models/sql/datastructures.py)`

Workaround:
Stay on Django 3.0.8

**Comment by ticosax** [comment]
Fixed in https://github.com/chibisov/drf-extensions/commit/8001a440c7322be26bbe2d16f3a334a8b0b5860b

**Comment by nikbora** [comment]
With Django 3.1 it might be worth releasing a new version with the fix to enable us to upgrade? (I assume this is the only issue so far)

**Comment by rosscdh** [comment]
+1 for new release

**Comment by cchacholiades** [comment]
I am having trouble importing the ExtendedSimpleRouter() due to this issue. I am using drf-extensions==0.6.0.

**Comment by brianhelba** [comment]
@auvipy Now that #290 is merged and Django 3.1 tests in #295 are passing, it seems like this issue is resolved. Can we please get a release of `drf-extensions`, for the benefit of all downstream users?

**Comment by TurnrDev** [comment]
`pip install -U git+git://github.com/chibisov/drf-extensions.git@8001a440c7322be26bbe2d16f3a334a8b0b5860b` < This solved my issue but it's not a great long term solution

**Comment by brianhelba** [comment]
@auvipy Ping again on a new release, please. This package is currently broken on Django 3.1, but a release should resolve it.

**Comment by Ouradze** [comment]
Hi, sorry for the noise but a new release would be much appreciated :) thanks in advance to you guys !

**Comment by TurnrDev** [comment]
I don't think we're getting the update pushed guys.

**Comment by auvipy** [comment]
in the mean time use pip to install from github master

**Comment by stevanmilic** [comment]
@auvipy why are we waiting for new release? It's normal to update the package to work with latest version of django

**Comment by jamiegau** [comment]
Yes, come on guys.  This has been languishing for weeks.  Issues have been addressed/fixed, just needs to be released.  What's the hold up?
It's a reasonable important piece of many projects that are now forced to hold at 3.0.8.  Pulling from upstream is messy and would need revisiting.  Would prefer to fix this once.

**Comment by ticosax** [comment]
@auvipy  is doing volunteering work. He's not entitled to do anything for us.
It exists a viable alternative to the lack of release, (installing from master branch), if you don't want to use this solution, that's your decision, but it shouldn't be used as a mean to harass the maintainers of the project.

Thank you @auvipy for maintaining this project, and take the rest you need when you need it.

**Comment by jamiegau** [comment]
@ticosax I find it strange that the fix is done and tested. but the final stage to push it into a release has not occured. if there is a reason for this, I expect the community would understand and be fine with it.  It has been 3 weeks.

**Comment by ticosax** [comment]
@jamiegau it takes time and energy to make a release. Merging a pull request is much easier than performing a release. Personally, I'm not surprised.
My point is, it is absolutely necessary to respect the pace of the maintainers. Given there is solutions, it is really not worth it, to ask for a release to be made sooner. The message has been sent, no need to insist.

**Comment by tuky** [comment]
haters gonna hate, monkeys gonna patch ;>

```python
from django.db.models.sql import datastructures
from django.core.exceptions import EmptyResultSet

datastructures.EmptyResultSet = EmptyResultSet
```

**Comment by MDziwny** [comment]
Can we help somehow to publish the new version?

**Comment by TurnrDev** [comment]
> Can we help somehow to publish the new version?

I suppose we should create the relevant changelog entries and bump the version number in a commit. Make a PR and then all the maintainer has to do is pull, test, publish :)

**Comment by ItsCalebJones** [comment]
Throwing a bump on it.

**Comment by thiennlinh** [comment]
> haters gonna hate, monkeys gonna patch ;>
> 
> ```python
> from django.db.models.sql import datastructures
> from django.core.exceptions import EmptyResultSet
> 
> datastructures.EmptyResultSet = EmptyResultSet
> ```

where does this code handle?

**Comment by tuky** [comment]
> > haters gonna hate, monkeys gonna patch ;>
> > ```python
> > from django.db.models.sql import datastructures
> > from django.core.exceptions import EmptyResultSet
> > 
> > datastructures.EmptyResultSet = EmptyResultSet
> > ```
> 
> where does this code handle?

you typically put monkey patches in a high level module file `__init__.py`, so the code is executed every time you use your app. so e.g. in `app.__init__`.

**Comment by thiennlinh** [comment]
> > > haters gonna hate, monkeys gonna patch ;>
> > > ```python
> > > from django.db.models.sql import datastructures
> > > from django.core.exceptions import EmptyResultSet
> > > 
> > > datastructures.EmptyResultSet = EmptyResultSet
> > > ```
> > 
> > 
> > where does this code handle?
> 
> you typically put monkey patches in a high level module file `__init__.py`, so the code is executed every time you use your app. so e.g. in `app.__init__`.

Tks, I have fixed the above error.

**Comment by mymtw** [comment]
@auvipy what the problem to release new version?

**Comment by domdinicola** [comment]
is this going to be released at some point?
is the project alive? :)

**Comment by TurnrDev** [comment]
> is this going to be released at some point?
Probably not
> is the project alive? :)
No, but I'm sure the community wouldn't be against a fork. I would be up for being a maintainer of said fork.

**Comment by domdinicola** [comment]
anyone maintaining a fork? releasing packages in pypi?

**Comment by auvipy** [comment]
sorry, lots of open-source backlogs. and new family. will push to pypi tomorrrow

**Comment by brianhelba** [comment]
@auvipy Thanks!

Are there any current contributors to this repo who could be promoted to co-maintainers? That should help to reduce the burden and risk on having a single maintainer.

**Comment by auvipy** [comment]
https://pypi.org/project/drf-extensions/0.7.0/, please try

**Comment by domdinicola** [comment]
@auvipy thanks and congrants

> sorry, lots of open-source backlogs. and new family. will push to pypi tomorrrow

**Comment by auvipy** [comment]
thanks :D married life is quite challenging so far!
