### ISSUE TITLE
Django Cron Abandoned

### ISSUE THREAD

**Issue by TJHeeringa** [chibisov/drf-extensions#305]
According to https://github.com/Tivix/django-cron/issues/158#issuecomment-648467312 the project is abandoned. It is a very useful package and it would be a shame it got lost. @auvipy Would it be possible to add it to this repo?

**Comment by auvipy** [comment]
yes, PR welcome. or I could fork the project and release a new version

**Comment by chibisov** [comment]
> yes, PR welcome. or I could fork the project and release a new version

I've just got email about this issues. How does cron project relates to rest framework extensions? I don't feel like it should be merged into this repo.

**Comment by TJHeeringa** [comment]
Rest Framework extensions is a collection of useful extensions for django rest. I see the djang cron project as such, however I realized the package django-cron does also work for project with only django and no DRF. So maybe it is not the best idea to merge it into this repo.

**Comment by auvipy** [comment]
> Rest Framework extensions is a collection of useful extensions for django rest. I see the djang cron project as such, however I realized the package django-cron does also work for project with only django and no DRF. So maybe it is not the best idea to merge it into this repo.

i can fork and release a new package in modified name.
