### ISSUE TITLE
500 error returns in case of invalid parent lookup

### ISSUE THREAD

**Issue by yurasavin** [chibisov/drf-extensions#333]
Hi! In `NestedViewSetMixin.filter_queryset_by_parents_lookups` method 404 error returns if `ValueError` occur while filtering queryset.
But in my case invalid value is passed for UUID field and `ValidationError` occur, so this error is not handled and 500 error returns. How about to add case for `ValidationError` and returns default drf 400 response or even the same 404 response?

I could implement this feature if you interested

**Comment by auvipy** [comment]
I would love to see that handled with a proper regression test

**Comment by yurasavin** [comment]
@auvipy here is it https://github.com/chibisov/drf-extensions/pull/334

**Comment by yurasavin** [comment]
https://github.com/chibisov/drf-extensions/pull/334

**Comment by yurasavin** [comment]
https://github.com/chibisov/drf-extensions/pull/334
