### ISSUE TITLE
Automatically determine `select_related` and `prefetch_related` on ModelSerializer

### ISSUE THREAD

**Issue by cancan101** [chibisov/drf-extensions#52]
What do you think about adding something along the lines of https://github.com/tomchristie/django-rest-framework/issues/1964 to drf-extensions? 

@thedrow offers a pretty good write-up on a workable approach: https://github.com/tomchristie/django-rest-framework/issues/1964#issuecomment-59645915

**Comment by chibisov** [comment]
By and large I think it's too magic. Closing this issue.
