### ISSUE TITLE
Smarter parents_query_lookups

### ISSUE THREAD

**Issue by cancan101** [chibisov/drf-extensions#56]
If the `lookup_field` of the ViewSet pointed to by a nested route is not set to `pk` then the `parents_query_lookups` should end with `__<lookup_field>`:

```python
router.register('people', views.PersonViewSet)
      .register(r'tests', views.TestUnderPersonViewSet, base_name="test", 
                parents_query_lookups=["person__uuid"])
```
where `TestUnderPersonViewSet` has its `lookup_field = 'uuid'`.

**Comment by auvipy** [comment]
1 year later, what are thoughts now?

**Comment by auvipy** [comment]
closing as lack of activities.
