### ISSUE TITLE
ExtendedDefaultRouter root view is polluted

### ISSUE THREAD

**Issue by cancan101** [chibisov/drf-extensions#57]
I am using `ExtendedDefaultRouter` with nested routes. Right now my root view is being polluted by the sub items: 
```
GET /api/
```
```json
{
    "people": "http://127.0.0.1:8000/api/people/", 
    "people/(?P<parent_lookup_person__uuid>[^/.]+)/tests": "http://127.0.0.1:8000/api/tests/",
    "tests": "http://127.0.0.1:8000/api/tests/"
}
```

**Comment by cancan101** [comment]
@kevin-brown Thoughts?

**Comment by kevin-brown** [comment]
@cancan101 looks like we're still waiting on @chibisov.

For what it's worth, you'd have this issue without the custom router now that DRF [also has the `try...except` code in place](https://github.com/tomchristie/django-rest-framework/blob/e9ac1bb78add68635e7f0881c16d2a3ddda2f1b5/rest_framework/routers.py#L299-L307).

**Comment by cancan101** [comment]
@kevin-brown:

The issue here is that `register` called on `NestedRegistryItem` adds to the `registry` of the underlying router rather than keeping a separate list of sub URLs.

This is different from how [drf-nested-routers works](https://github.com/alanjds/drf-nested-routers/blob/master/rest_framework_nested/routers.py#L47) where each nested router keeps track of the URLs (routes) at its level.

**Comment by auvipy** [comment]
closing
