### ISSUE TITLE
ListModelViewSet

### ISSUE THREAD

**Issue by cancan101** [chibisov/drf-extensions#59]
Consider adding the following to viewsets:

``` python

class ListModelViewSet(mixins.ListModelMixin,
                       GenericViewSet):
    """
    A viewset that provides default `list()` actions.
    """
    pass
```

This would complement `ReadOnlyModelViewSet`.

See: https://github.com/tomchristie/django-rest-framework/issues/2113

**Comment by auvipy** [comment]
is the issue still valid in your thought?

**Comment by auvipy** [comment]
feel free to send PR
