### ISSUE TITLE
Mixin to include ETag in list responses

### ISSUE THREAD

**Issue by stevelacey** [chibisov/drf-extensions#62]
Just wondering whether it makes sense, or there's scope, to add a mixin that includes the ETag for each result in a list response, say as a key in the JSON– I essentially want to get a bunch of a results, and use the ETag from each to If-Match PATCH them.

Is that a sensible approach? Is it easy to add? Should there be a mixin in this repo to add that?

**Comment by chibisov** [comment]
I'm closing it for now.

**Comment by stevelacey** [comment]
If anyone else comes across this, I went for doing the list request just to get the pks, then individual detail requests to get the ETag, then If-Match requests to update the resources... inefficient, but does the job, and I'm not going to lose sleep over it.
