### ISSUE TITLE
PartialUpdateSerializerMixin `.save_object()` that is no longer compatible with REST framework 3.

### ISSUE THREAD

**Issue by davidmir** [chibisov/drf-extensions#66]
Hi,

I'm getting this error using PartialUpdateSerializerMixin with DRF 3.0:

AssertionError: Serializer `tasks.serializers.task.TaskSerializer` has old-style version 2 `.save_object()` that is no longer compatible with REST framework 3. Use the new-style `.create()` and `.update()` methods instead.

Is this a bug?

Thanks in advance

**Comment by chibisov** [comment]
It's a bug, related to #39

I'm working on it. Hope will fix it this week.

**Comment by chibisov** [comment]
@davidmir, I've pushed fix to master branch. It would be cool if you tried it before I released new version.
