### ISSUE TITLE
nested permissions with nested routers

### ISSUE THREAD

**Issue by neokree** [chibisov/drf-extensions#78]
Hi,
Nested routers filter his parent id using the parents_query_lookups parameter, but how I can access to that resource for creating my permissions? 

Based on your example into [docs](http://chibisov.github.io/drf-extensions/docs/#nested-routes):
For <code>GroupViewSet</code> I want to create a permission that allow to CREATE a new group only if the user authenticated id is equal to the user id selected by the previous viewset. 

There is a way to do that?

**Comment by chibisov** [comment]
Hi. You can extend `GroupViewSet` for nested usage, like I've described in [this](https://github.com/chibisov/drf-extensions/issues/15#issuecomment-47745649) comment.

**Comment by neokree** [comment]
Thanks a lot!
