### ISSUE TITLE
@list_route name in Extended routers doesn't match that of DRF routers

### ISSUE THREAD

**Issue by caffodian** [chibisov/drf-extensions#79]
Hi, sorry if this is covered somewhere already, I couldn't find anything in the documentation.

Is there a reason why @list_route are named differently in the extended routers compared to the DRF built in routers?

DRF uses `{basename}-{methodname}` for both detail_route and list_route [router doc](http://www.django-rest-framework.org/api-guide/routers/#extra-link-and-actions) , whereas drf-extensions routers name them as `{basename}-{methodnamehyphen}-list` which is an extra gotcha for upgrading to using an extended router.

I'm currently working on a fix, but wanted to submit the issue in case this was due to something I'm unaware of.

thanks!

**Comment by chibisov** [comment]
DRF-extension's [collection level controllers](http://chibisov.github.io/drf-extensions/docs/#collection-level-controllers) had been developed before DRF's '@list_route'

You must use DRF's `@list_route`, because DRF-extension's decorator is in pending deprecation and will be removed in next releases.

**Comment by caffodian** [comment]
Yes - I am using DRF's list_route.  Are these not usable with the ExtendedRouterMixin?  I was hoping to add nested routes to an existing project, though I guess I could just make another Router that only used the NestedRouterMixin but not the ExtendedActionLinkRouterMixin.  

If I am not supposed to use @list_route with ExtendedRouterMixin then you can disregard the rest. ;)

**Comment by chibisov** [comment]
If you want to use nesting facilities you should mixin [NestedRouterMixin](http://chibisov.github.io/drf-extensions/docs/#nested-router-mixin) into your router.
