### ISSUE TITLE
PaginationKeyBit Incopatible with DRF 3.1

### ISSUE THREAD

**Issue by mlavin** [chibisov/drf-extensions#92]
`page_kwarg` and `paginate_by_param` are no longer set on the view instance by default in favor of new the `pagination_class` http://www.django-rest-framework.org/topics/3.1-announcement/#pagination This means that the `PaginationKeyBit` does not take into account the pagination when generating the cache keys for the listing views.

**Comment by pdvorchik** [comment]
Any update on this issue?  Definitely a frustrating problem.
